const find = selector => document.querySelector(selector);
const escape = value => String(value ?? '').replace(/[&<>"']/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const money = value => new Intl.NumberFormat('en-PH',{style:'currency',currency:'PHP',maximumFractionDigits:0}).format(value);
const date = value => new Date(`${value}T12:00:00`).toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'});
const dayValue = value => `${value.getFullYear()}-${String(value.getMonth()+1).padStart(2,'0')}-${String(value.getDate()).padStart(2,'0')}`;
const statusLabel = value => value.toLowerCase().replaceAll('_',' ');
const badge = value => `<span class="badge ${escape(value)}">${escape(statusLabel(value))}</span>`;
let staff, bookings = [], rooms = [], today = '', view = 'dashboard', selected, busy = false;
let calendarMonth = new Date(), search = '', filter = '', roomFilter = '', roomDate = '';
async function request(path, options = {}) {
  const response = await fetch(path,{...options,headers:{'Content-Type':'application/json',...options.headers}});
  const data = await response.json();
  if (!response.ok) { if (response.status === 401 && staff) signedOut(); throw new Error(data.error || 'Could not complete the request.'); }
  return data;
}
function signedOut(){staff=undefined;find('#workspace').hidden=true;find('#login-screen').hidden=false;find('#booking-dialog').close();bookings=[];find('#view-content').replaceChildren();}
function roomName(id){return rooms.find(room=>room.id===id)?.name || id;}
const names = booking => booking.dogName+(booking.guests===2?` & ${booking.sibling}`:'');
const active = booking => ['PENDING','CONFIRMED','CHECKED_IN'].includes(booking.status);
const empty = text => `<div class="empty"><strong>A little breathing room.</strong>${escape(text)}</div>`;
function table(rows){return rows.length?`<div class="table-wrap"><table><thead><tr><th>GUEST</th><th>STAY</th><th>ROOM</th><th>STATUS</th><th>TOTAL · UNPAID</th></tr></thead><tbody>${rows.map(b=>`<tr><td><button class="booking-link" data-booking="${b.id}">${escape(names(b))}</button><small>${escape(b.reference)} · ${escape(b.owner)}</small></td><td>${date(b.checkIn)}<small>to ${date(b.checkOut)} · ${b.nights} nights</small></td><td>${escape(roomName(b.room))}</td><td>${badge(b.status)}</td><td>${money(b.total)}</td></tr>`).join('')}</tbody></table></div>`:empty('No bookings match this view.');}
function cards(){const occupied=bookings.filter(b=>active(b)&&b.checkIn<=today&&b.checkOut>today);return `<div class="stat-grid">${[
['Pending requests',bookings.filter(b=>b.status==='PENDING').length,'Waiting for staff confirmation'],
['Arriving today',bookings.filter(b=>b.checkIn===today&&b.status==='CONFIRMED').length,'Ready for a warm welcome'],
['Heading home',bookings.filter(b=>b.checkOut===today&&b.status==='CHECKED_IN').length,'Checked in · due out today'],
['Rooms reserved',`${occupied.length} / ${rooms.reduce((sum,r)=>sum+r.capacity,0)}`,'Today · includes pending requests'],
].map(([label,value,note])=>`<article class="stat"><p>${label}</p><strong>${value}</strong><small>${note}</small></article>`).join('')}</div>`;}
function toolbar(){return `<div class="toolbar"><label>Find a guest or reference<input id="search" type="search" value="${escape(search)}" placeholder="Dog, owner, email, reference…"></label><label>Status<select id="status-filter"><option value="">All statuses</option>${['PENDING','CONFIRMED','CHECKED_IN','CHECKED_OUT','CANCELLED','NO_SHOW'].map(s=>`<option ${filter===s?'selected':''} value="${s}">${statusLabel(s)}</option>`).join('')}</select></label><label>Room<select id="room-filter"><option value="">All rooms</option>${rooms.map(r=>`<option ${roomFilter===r.id?'selected':''} value="${r.id}">${escape(r.name)}</option>`).join('')}</select></label></div>`;}
function matching(){const text=search.toLowerCase();return bookings.filter(b=>(!filter||b.status===filter)&&(!roomFilter||b.room===roomFilter)&&[names(b),b.owner,b.email,b.reference].some(value=>value.toLowerCase().includes(text)));}
function calendar(){const year=calendarMonth.getFullYear(),month=calendarMonth.getMonth();let cells=['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].map(day=>`<div class="calendar-label">${day}</div>`).join('');const leading=(new Date(year,month,1).getDay()+6)%7;for(let i=0;i<leading;i++)cells+='<div class="calendar-day"></div>';for(let day=1;day<=new Date(year,month+1,0).getDate();day++){const value=dayValue(new Date(year,month,day));const rows=matching().filter(b=>active(b)&&b.checkIn<=value&&b.checkOut>value);cells+=`<div class="calendar-day ${value===today?'today':''}"><span>${day}</span>${rows.map(b=>`<button class="calendar-booking ${b.status}" data-booking="${b.id}" title="${escape(names(b)+' · '+roomName(b.room))}">${escape(names(b))}</button>`).join('')}</div>`;}return `<div class="calendar-toolbar"><button id="previous-calendar" aria-label="Previous month">←</button><h2>${calendarMonth.toLocaleDateString('en-GB',{month:'long',year:'numeric'})}</h2><button id="next-calendar" aria-label="Next month">→</button></div><p class="helper">Reserved nights, including pending requests. Check-out day is available for a new arrival.</p><div class="calendar-scroll"><div class="calendar-grid">${cells}</div></div>`;}
function roomCards(){
  const selectedDate=roomDate||today;
  return `<div class="toolbar room-date-toolbar"><label>Reservation date<input id="room-date" type="date" value="${escape(selectedDate)}"></label><button class="secondary" id="rooms-today">Today</button></div><p class="helper">Rooms reserved for the night of ${date(selectedDate)}. Pending requests, confirmed stays, and checked-in guests hold a room; check-out day is available.</p><div class="room-cards">${rooms.map(r=>{
    const held=bookings.filter(b=>active(b)&&b.room===r.id);
    const used=held.filter(b=>b.checkIn<=selectedDate&&b.checkOut>selectedDate).length;
    const upcoming=held.filter(b=>b.checkIn>selectedDate&&b.status==='CONFIRMED').length;
    return `<article class="room-card"><span class="eyebrow">OVERNIGHT STAYS</span><h2>${escape(r.name)}</h2><strong>${money(r.price)} / night</strong><p>Up to ${r.dogs} ${r.dogs===1?'dog':'dogs from the same household'}${r.id==='cozy'?' · small or medium':''}</p><div class="progress"><span style="width:${Math.min(100,used/r.capacity*100)}%"></span></div><small>${used} of ${r.capacity} rooms reserved ${selectedDate===today?'today':'on '+date(selectedDate)}</small><small class="upcoming-reservations">${upcoming} upcoming confirmed ${upcoming===1?'stay':'stays'} after this date</small></article>`;
  }).join('')}</div><p class="helper">These are starter capacities. Set your real inventory and rates before going live. All amounts are PHP; payments are not connected.</p>`;
}
function arrivalsView(){
  const ordered=(rows,key)=>rows.sort((a,b)=>a[key].localeCompare(b[key]));
  const futureDepartures=ordered(bookings.filter(b=>b.status==='CHECKED_IN'&&b.checkOut>today),'checkOut');
  const nextDeparture=futureDepartures[0]?.checkOut;
  const nextDepartureCount=futureDepartures.filter(b=>b.checkOut===nextDeparture).length;
  const departureEmpty=nextDeparture?`No checked-in guests are due to leave today. Next departure: ${date(nextDeparture)} · ${nextDepartureCount} checked-in ${nextDepartureCount===1?'stay':'stays'}.`:'No checked-in guests are due to leave today.';
  const section=(title,note,rows,message)=>`<div class="card"><h2>${title}</h2><p class="helper">${note}</p>${rows.length?table(rows):empty(message)}</div>`;
  return section('Arrivals due today',`Arrival date ${date(today)} or earlier · confirmed and awaiting check-in`,ordered(bookings.filter(b=>b.status==='CONFIRMED'&&b.checkIn<=today),'checkIn'),'No confirmed guests are due to check in today.')
    +section('Departures due today',`Departure date ${date(today)} or earlier · currently checked in`,ordered(bookings.filter(b=>b.status==='CHECKED_IN'&&b.checkOut<=today),'checkOut'),departureEmpty)
    +section('Upcoming arrivals','Confirmed stays with a future arrival date. Check-in opens on the arrival date.',ordered(bookings.filter(b=>b.status==='CONFIRMED'&&b.checkIn>today),'checkIn'),'No upcoming confirmed arrivals.')
    +section('Upcoming departures','Planned departures for confirmed stays and guests currently checked in.',ordered(bookings.filter(b=>['CONFIRMED','CHECKED_IN'].includes(b.status)&&b.checkOut>today),'checkOut'),'No upcoming departures.');
}
function render(){
  const titles={dashboard:['A good day at the Haus.',"A little overview of who's coming, staying, and heading home."],bookings:['Their holidays, all together.','Review requests, confirm stays, and keep every detail close.'],calendar:['Make room for happy stays.','A month of little holidays, with every reserved night in view.'],arrivals:['Hello. And see you soon.','Today’s check-ins and check-outs, plus upcoming confirmed stays.'],guests:['Good dogs. Lovely people.','Guest records collected from booking requests.'],rooms:['A place for every little personality.','See reservations by stay date and the nightly rates used by the server.']};
  find('#page-title').textContent=titles[view][0];find('#page-subtitle').textContent=titles[view][1];find('#view-label').textContent=view==='dashboard'?'Overview':view[0].toUpperCase()+view.slice(1);
document.querySelectorAll('[data-view]').forEach(button=>{button.classList.toggle('active',button.dataset.view===view);if(button.dataset.view===view)button.setAttribute('aria-current','page');else button.removeAttribute('aria-current');});
  const content=find('#view-content');
  if(view==='dashboard')content.innerHTML=cards()+`<div class="card"><div class="card-heading"><h2>Requests to look after</h2><p>Pending confirmation</p></div>${table(bookings.filter(b=>b.status==='PENDING'))}</div><div class="card"><div class="card-heading"><h2>At the Haus today</h2><p>${date(today)}</p></div>${table(bookings.filter(b=>b.status==='CHECKED_IN'))}</div>`;
  if(view==='bookings')content.innerHTML=toolbar()+`<div class="card" id="booking-results">${table(matching())}</div>`;
  if(view==='calendar')content.innerHTML=toolbar()+`<div id="calendar-results">${calendar()}</div>`;
  if(view==='arrivals')content.innerHTML=arrivalsView();
  if(view==='guests'){const people=new Map();for(const b of [...bookings].reverse()){const person=people.get(b.email)||{owner:b.owner,phone:b.phone,email:b.email,dogs:new Set(),stays:0};person.owner=b.owner;person.phone=b.phone;person.dogs.add(names(b));person.stays++;people.set(b.email,person);}content.innerHTML=`<div class="card"><h2>People &amp; their best friends</h2>${people.size?`<div class="table-wrap"><table><thead><tr><th>PERSON</th><th>CONTACT</th><th>DOGS</th><th>REQUESTS</th></tr></thead><tbody>${[...people.values()].map(p=>`<tr><td>${escape(p.owner)}</td><td>${escape(p.email)}<small>${escape(p.phone||'No phone provided')}</small></td><td>${escape([...p.dogs].join(', '))}</td><td>${p.stays}</td></tr>`).join('')}</tbody></table></div>`:empty('Guest records appear after the first booking request.')}</div>`;}
  if(view==='rooms')content.innerHTML=roomCards();
}
async function refresh(){find('#refresh').disabled=true;find('#portal-message').textContent='';try{const [result,config]=await Promise.all([request('/api/admin/bookings'),request('/api/config')]);bookings=result.bookings;rooms=config.rooms;today=config.today;render();}catch(error){find('#portal-message').textContent=error.message;}finally{find('#refresh').disabled=false;}}
async function start(result){staff=result.staff;const config=await request('/api/config');rooms=config.rooms;today=config.today;find('.sidebar .local-pill').textContent=config.mode==='neon'?'NEON POSTGRES':'LOCAL DATABASE';calendarMonth=new Date(`${today}T12:00:00`);calendarMonth.setDate(1);find('#staff-label').textContent=`${staff.email} · ${statusLabel(staff.role)}`;find('#login-screen').hidden=true;find('#workspace').hidden=false;await refresh();}
function passwordVisibility(visible){find('#staff-password').type=visible?'text':'password';const toggle=find('#password-toggle');toggle.setAttribute('aria-label',visible?'Hide password':'Show password');toggle.setAttribute('aria-pressed',String(visible));toggle.querySelector('.eye-slash').toggleAttribute('hidden',!visible);}
find('#password-toggle').addEventListener('click',()=>passwordVisibility(find('#staff-password').type==='password'));
find('#login-form').addEventListener('reset',()=>passwordVisibility(false));
find('#login-form').addEventListener('submit',async event=>{event.preventDefault();const button=event.target.querySelector('[type="submit"]');button.disabled=true;find('#login-error').textContent='';passwordVisibility(false);try{await start(await request('/api/auth/login',{method:'POST',body:JSON.stringify({email:event.target.elements.email.value,password:event.target.elements.password.value})}));event.target.reset();}catch(error){find('#login-error').textContent=error.message;}finally{button.disabled=false;}});
find('#logout').addEventListener('click',async()=>{try{await request('/api/auth/logout',{method:'POST',body:'{}'});signedOut();}catch(error){find('#portal-message').textContent=error.message;}});
find('#refresh').addEventListener('click',refresh);
find('#menu-button').addEventListener('click',()=>{const open=find('#workspace').classList.toggle('menu-open');find('#menu-button').setAttribute('aria-expanded',String(open));find('#menu-button').setAttribute('aria-label',open?'Close staff menu':'Open staff menu');});
document.querySelectorAll('[data-view]').forEach(button=>button.addEventListener('click',()=>{view=button.dataset.view;search=filter=roomFilter='';render();find('#workspace').classList.remove('menu-open');find('#menu-button').setAttribute('aria-expanded','false');find('#menu-button').setAttribute('aria-label','Open staff menu');}));
find('#view-content').addEventListener('input',event=>{if(event.target.id==='search'){search=event.target.value;const target=find(view==='calendar'?'#calendar-results':'#booking-results');target.innerHTML=view==='calendar'?calendar():table(matching());}});
find('#view-content').addEventListener('change',event=>{if(event.target.id==='room-date'){roomDate=event.target.value;render();return;}if(event.target.id==='status-filter')filter=event.target.value;if(event.target.id==='room-filter')roomFilter=event.target.value;render();});
find('#view-content').addEventListener('click',event=>{const button=event.target.closest('button');if(!button)return;if(button.id==='rooms-today'){roomDate='';render();return;}if(button.dataset.booking)openDetail(button.dataset.booking);if(button.id==='previous-calendar'||button.id==='next-calendar'){calendarMonth.setMonth(calendarMonth.getMonth()+(button.id==='next-calendar'?1:-1));render();}});
async function openDetail(id){selected=bookings.find(b=>b.id===id);if(!selected)return;find('#detail-error').textContent='';renderDetail();if(!find('#booking-dialog').open)find('#booking-dialog').showModal();find('#detail-history').textContent='Loading activity…';try{const result=await request(`/api/admin/bookings/${id}/history`);if(selected?.id===id)find('#detail-history').innerHTML=result.history.map(item=>`<div class="history-item">${escape(item.action)}<small>${escape(item.actor)} · ${new Date(item.created_at).toLocaleString('en-PH')}</small></div>`).join('');}catch(error){find('#detail-history').textContent=error.message;}}
function renderDetail(){const b=selected;find('#booking-detail').innerHTML=`<h2 id="detail-title">${escape(names(b))}</h2><p>${escape(b.reference)} ${badge(b.status)}</p><div class="detail-grid">${[['Check in',date(b.checkIn)],['Check out',date(b.checkOut)],['Room',roomName(b.room)],['Stay total · unpaid',money(b.total)],['Human',b.owner],['Email',b.email],['Phone',b.phone||'Not provided'],['Dog details',`${b.breed} · ${b.size} · ${b.guests} dog(s)`]].map(([label,value])=>`<div><span>${label}</span><strong>${escape(value)}</strong></div>`).join('')}</div><h3>Care notes</h3><p class="care-note">${escape(b.notes||'No special care notes provided.')}</p><p class="helper">A confirmation approves the stay without collecting payment. Payments and emails are not connected.</p>`;const transitions={PENDING:[['CONFIRMED','Confirm stay'],['CANCELLED','Cancel request']],CONFIRMED:[['CHECKED_IN','Check in'],['CANCELLED','Cancel stay'],['NO_SHOW','Mark no-show']],CHECKED_IN:[['CHECKED_OUT','Check out']]};find('#detail-actions').innerHTML=staff.role==='CARE_STAFF'?'<p class="helper">Your care role can view details. Front desk or admin handles status changes.</p>':(transitions[b.status]||[]).map(([status,label])=>`<button class="${status==='CANCELLED'||status==='NO_SHOW'?'secondary':'primary'}" data-status="${status}">${label}</button>`).join('');}
find('#detail-actions').addEventListener('click',async event=>{const button=event.target.closest('[data-status]');if(!button||busy)return;if(!confirm(`${button.textContent} for ${names(selected)}?`))return;busy=true;find('#detail-actions').querySelectorAll('button').forEach(b=>b.disabled=true);find('#detail-error').textContent='';try{const result=await request(`/api/admin/bookings/${selected.id}`,{method:'PATCH',body:JSON.stringify({status:button.dataset.status,version:selected.version})});bookings=bookings.map(b=>b.id===result.booking.id?result.booking:b);render();await openDetail(result.booking.id);}catch(error){find('#detail-error').textContent=error.message;await refresh();}finally{busy=false;find('#detail-actions').querySelectorAll('button').forEach(b=>b.disabled=false);}});
find('#close-dialog').addEventListener('click',()=>find('#booking-dialog').close());
document.addEventListener('keydown',event=>{if(event.key==='Escape'){find('#workspace').classList.remove('menu-open');find('#menu-button').setAttribute('aria-expanded','false');find('#menu-button').setAttribute('aria-label','Open staff menu');}});
request('/api/auth/session').then(start).catch(error=>{if(error.message!=='Please sign in to the staff portal.')find('#login-error').textContent='The booking server is unavailable. Please try again.';});
